---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
  fixme:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
   - "**.js"
   - "**.css"
   - "**.php"
   - "**.ini"
exclude_paths:
   - "site/"
   - "doc/"
   - "/protected/framework/"
   - "/protected/vendors/"
   - "/vendors/"
   - "**.bat"